# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89a134a6235c2be367f55b413cb25f89ccbc53fdeaf86282525a03e8bd90c516c435630d3f22bdc0b37002d2d36a07d8a74e3b326c36b7a8efdb14a19548fbd0

test:
  secret_key_base: 0d7fb9a493acda4ce10ed9443f1a2060e14f2056c77e1c534cbd5faa4cc669fe73ecc506bd1d966d9a70871af4dd69700cc91432cf17bf6527a3843e0c3875aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
